version: '3'

services:
  app:
    build:
      context: ./src/
      dockerfile: Dockerfile
    ports:
      - "3200:3200"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Emotae06
      MYSQL_DATABASE: nutrifit_hub_db
    ports:
      - "4406:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
